### ISSUE TITLE
Openbabel build fails for Linux

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/conda-recipes#2]
This is the error log:

```
Scanning dependencies of target bindings_python
make[2]: *** No rule to make target `/home/connie/anaconda/envs/_build_placehold_placehold_placehold_placehold_placeh/lib/libpython2.7.dylib', needed by `lib/_openbabel.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 99%] Building CXX object scripts/CMakeFiles/bindings_python.dir/python/openbabel-python.cpp.o
Linking CXX executable ../bin/test_stereoperception
[ 99%] Built target test_stereoperception
Linking CXX executable ../bin/test_tetrahedral
Linking CXX executable ../bin/test_tetranonplanar
Linking CXX executable ../bin/test_uniqueid
Linking CXX executable ../bin/test_tetraplanar
[ 99%] Built target test_tetrahedral
[ 99%] [ 99%] Built target test_tetranonplanar
Built target test_uniqueid
[ 99%] Built target test_tetraplanar
Linking CXX executable ../bin/test_stereo
Linking CXX executable ../bin/test_unitcell
[ 99%] Built target test_unitcell
[ 99%] Built target test_stereo
make[1]: *** [scripts/CMakeFiles/bindings_python.dir/all] Error 2
make: *** [all] Error 2
Command failed: /bin/bash -x -e /home/connie/Research/Code/conda-recipes/openbabel/build.sh
```

**Comment by rwest** [comment]
Does that actually show what failed?
Oh, is it trying to make `/home/connie/anaconda/envs/_build_placehold_placehold_placehold_placehold_placeh/lib/libpython2.7.dylib`  for some reason?

Perhaps ask on https://github.com/conda/conda-recipes/pull/310 for help if you can't figure it out quickly.

**Comment by connie** [comment]
So I was able to get the python bindings to build by changing the line in build.sh to

```
-DPYTHON_LIBRARY=$PREFIX/lib/libpython$PY_VER.so
```

but now I also run into the same error as that other user:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/connie/anaconda/lib/python2.7/site-packages/pybel.py", line 72, in <module>
    informats = _formatstodict(_obconv.GetSupportedInputFormat())
  File "/home/connie/anaconda/lib/python2.7/site-packages/pybel.py", line 68, in _formatstodict
    broken = [(x,y.strip()) for x,y in broken]
ValueError: need more than 1 value to unpack
```

I'll be commenting a bit more on the conda-recipes thread you mentioned.
